learning_log/learning_log/urls.py
"""learning_log URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin

from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    path(r'', include(('learning_logs.urls', "learning_logs"),
                      namespace='learning_logs'))
]

learning_log/learning_logs/urls.py
'''
@Description: 
@Version: 1.0
@Autor: Henggao
@Date: 2020-03-19 16:33:04
@LastEditors: Henggao
@LastEditTime: 2020-04-20 15:35:05
'''

"""定义learning_logs的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # 主页
    url(r"^$", views.index, name='index'),
    # 显示所有的主题
    url(r'^topics/$',views.topics,name="topics"),
    # 特定主题的详细页面
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name="topic"),
    # 用于添加新主题的网页
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    #用于添加新条目的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry,name='new_entry'),
    # 用于编辑条目的页面
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry',)
]

learning_log/users/urls.py
'''
@Description: 
@Version: 1.0
@Autor: Henggao
@Date: 2020-04-22 12:53:37
@LastEditors: Henggao
@LastEditTime: 2020-04-22 20:03:37
'''
'''为应用程序users定义url模式'''

# from django.contrib.auth import login

from . import views
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'users'
urlpatterns = [
    # 登录界面
    # url(r'^login/$', login,
    #     {'template_name': 'users/login.html'}, name='login'),
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    # 注销
    url(r'^login/$', LogoutView.as_view(), name='logout'),
    # # Registration page.
    # path('register/', views.register, name='register'),
    # 注册页面
    url(r'^register/$', views.register, name='register'),
]

learning_log/learning_logs/models.py
'''
@Description: 
@Version: 1.0
@Autor: Henggao
@Date: 2020-03-18 18:25:39
@LastEditors: Henggao
@LastEditTime: 2020-03-19 12:54:22
'''
from django.db import models

# Create your models here.
class Topic(models.Model):
    '''用户学习的主题'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        '''返回模型字符串表示'''
        return self.text

class Entry(models.Model):
    '''学到的有关某个主题的具体知识'''
    topic = models.ForeignKey("Topic",on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        '''返回模型的字符串表示'''
        return self.text[:50] + "..."
        

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
'''
@Description: 
@Version: 1.0
@Autor: Henggao
@Date: 2020-04-17 16:16:18
@LastEditors: Henggao
@LastEditTime: 2020-04-19 12:39:51
'''
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_log/learning_logs/views.py
'''
@Description: 
@Version: 1.0
@Autor: Henggao
@Date: 2020-03-18 18:25:39
@LastEditors: Henggao
@LastEditTime: 2020-04-20 15:28:05
'''
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Topic,Entry
from .forms import TopicForm,EntryForm

# Create your views here.


def index(request):
    """学习笔记主页"""
    return render(request, "learning_logs/index.html")

def topics(request):
    """显示所有主题"""
    topics = Topic.objects.order_by("date_added")
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request,topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

def new_topic(request):
    '''添加新的主题'''
    if request.method !=  'POST':
        # 未提交数据：创建一个新的表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)

def new_entry(request,topic_id):
    '''在特定的主题中添加新条目'''
    topic = Topic.objects.get(id = topic_id)

    if request.method != 'POST':
        # 未提交数据，创建一个空表单
        form = EntryForm()
    else:
        # POST提交数据，随数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

def edit_entry(request,entry_id):
    '''编辑既有条目'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(isinstance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
        
        context = {'entry':entry,'topic':topic,'form':form}
        return render(request ,'learning_logs/edit_entry.html',context)

learning_log/users/views.py
'''
@Description: 
@Version: 1.0
@Autor: Henggao
@Date: 2020-04-20 16:50:45
@LastEditors: Henggao
@LastEditTime: 2020-04-22 19:13:40
'''
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout

def logout_view(request):
    '''注销用户'''
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

learning_log/learning_logs/templates/learning_logs/base.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-03-19 17:04:06
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-22 19:15:56
 -->
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a> -
    {% if user.is_authenticated %}
        Hello,{{user.username}}.
        <a href="{url 'users:logout' %}">log out</a>
    {% else %}
    <a href="{% url 'users:login' %}" login in></a>
    {% endif %}
</p>
{% block content %}{% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_entry.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-04-20 15:28:24
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-20 15:29:01
 -->
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-03-19 16:41:44
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-14 19:17:56
 -->
 {% extends "learning_logs/base.html" %}
 {% block content %}
   <p>Learning Log helps you keep track of your learning, for any topic you're
   learning about.</p>
 {% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-04-20 12:49:51
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-20 13:47:28
 --> 
{% extends "learning_logs/base.html" %}

{% block content %}

 <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

 <p>Add a new entry:</p>
 <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button name="sumbit">add entry</button>
 </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-04-19 11:40:04
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-19 12:26:33
 -->

{% extends "learning_logs/base.html" %}

{% block content %}
 <p>Add a new topic: </p>

 <form action="{% url 'learning_logs:new_topic' %}"  method="POST">
     {% csrf_token %}
     {{ form.as_p}}
     <button name="submit">add topic</button>
 </form>

 {% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-03-19 18:22:45
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-20 15:33:57
 -->
{% extends "learning_logs/base.html" %}

{% block content %}

 <p>Topic: {{ topic}}</p>

 <p>Entries:</p>
 <p>
     <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
 </p>
 <ul>
     {%for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i'}}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
            </p>
        </li>
    {% empty %}
        <li>
            There are no entries for this topic yet.
        </li>
    {% endfor %}
 </ul>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-03-19 17:38:57
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-19 12:18:20
 -->
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Topics</p>

  <ul>
      {% for topic in topics %}
        <!-- <li>{{ topic}}</li> -->
        <li>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
          </li>
      {% empty %}
        <li>No topics have been added yet.</li>
      {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topics'%}">Add a new topic:</a>

{% endblock content %}

learning_log/users/templates/users/logged_out.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-04-22 19:54:02
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-22 19:54:16
 -->
{% extends "learning_logs/base.html" %}
{% block content %}
<p>You have been logged out. Thank you for visiting!</p>
{% endblock content %}

learning_log/users/templates/users/login.html
<!--
 * @Description: 
 * @Version: 1.0
 * @Autor: Henggao
 * @Date: 2020-04-22 13:19:44
 * @LastEditors: Henggao
 * @LastEditTime: 2020-04-22 14:58:57
 -->
{% extends "learning_logs/base.html" %}
{% block content %}
    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">log in</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}